eureka:
  instance:
    preferIpAddress: true 
    hostname: localhost
  client:
    registerWithEureka: true 
    fetchRegistry: false 
    serviceUrl:
      defaultZone: http://192.168.88.131:8761/eureka/  
spring:
  application:
    name: userservice
  datasource:
    url: jdbc:mysql://localhost/my_mysql
    password: 789456123
    driver-class-name: com.mysql.jdbc.Driver
    username: tan_tan
server:
  port: 8880
